- type: job
  id: SPComplexScientist
  name: job-name-SPComplexScientist
  description: job-description-SPComplexScientist
  playTimeTracker: SPJobScientist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10h
    - !type:SpeciesRequirement
      species:
      - Human
  startingGear: SPComplexScientistGear
  icon: "JobIconScientist"
#  supervisors: job-supervisors-rd
  access:
  - Cryogenics
  - Medical
  - Research
  - Maintenance
  - External
  - Chemistry

- type: startingGear
  id: SPComplexScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    back: ClothingBackpackSatchelGenetics
    shoes: ClothingShoesColorWhite
    outerClothing: ClothingOuterCoatLab
    ears: ClothingHeadsetScience
    gloves: ClothingHandsGlovesNitrile
    pocket1: Shoker
    belt: BoxFolderClipboardThreePapers
    id: SciencePDA
  storage:
    back:
    - InjectorGunFilled
    - InjectorShellTranquilizer
    - InjectorShellTranquilizer
    - InjectorShellTranquilizer
    - InjectorShellAntisomnin
    - InjectorShellAntisomnin
    - SyringeDormitive
    - HandLabeler
