- type: job
  id: SPComplexTestSubjects
  name: job-name-SPComplexTestSubjects
  description: job-description-SPComplexTestSubjects
  playTimeTracker: SPJobTestSubjects
#  icon: "JobIcon"
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10h
    - !type:SpeciesRequirement
      species:
      - Albino
      - BoldMilky
      - Speciman
      - Milky

